# Generated by Django 4.2.16 on 2024-11-22 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.IntegerField(verbose_name='공시제출월')),
                ('fin_co_no', models.IntegerField()),
                ('kor_co_nm', models.CharField(max_length=50, verbose_name='은행이름')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField(verbose_name='만기후이자율')),
                ('spcl_cnd', models.TextField(verbose_name='우대사항')),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField()),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(null=True)),
                ('dcls_strt_day', models.IntegerField(verbose_name='공시 시작일')),
                ('dcls_end_day', models.IntegerField(null=True, verbose_name='공시 종료일')),
                ('fin_co_subm_day', models.IntegerField(verbose_name='금융회사 제출일')),
            ],
            options={
                'verbose_name': '적금 상품',
                'verbose_name_plural': '적금 상품 목록',
            },
        ),
        migrations.CreateModel(
            name='UserSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=50)),
                ('product', models.TextField()),
                ('mtrt', models.FloatField()),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField()),
                ('max_limit', models.FloatField()),
                ('intr', models.FloatField()),
                ('intr_rate_type', models.CharField(max_length=10, verbose_name='금리 유형')),
                ('rsrv_type', models.CharField(max_length=10, verbose_name='적립유형')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('savings_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savingproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.IntegerField()),
                ('fin_co_no', models.IntegerField()),
                ('intr_rate_type', models.CharField(max_length=10, verbose_name='금리 유형')),
                ('intr_rate_type_nm', models.TextField()),
                ('rsrv_type', models.CharField(max_length=10, verbose_name='적립유형')),
                ('rsrv_type_nm', models.TextField()),
                ('save_trm', models.IntegerField(verbose_name='저축기간')),
                ('intr_rate', models.FloatField(verbose_name='최저금리')),
                ('intr_rate2', models.FloatField(verbose_name='최고금리')),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savingproduct', to_field='fin_prdt_cd')),
            ],
            options={
                'verbose_name': '상품 상세 정보',
                'verbose_name_plural': '상품 정보',
            },
        ),
    ]
