# Generated by Django 4.2.16 on 2024-11-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaving',
            name='save_trm',
            field=models.IntegerField(verbose_name='저축기간'),
            preserve_default=False,
        ),
    ]
