# Generated by Django 4.2.16 on 2024-11-21 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSavings',
            new_name='UserSaving',
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='dcls_end_day',
            field=models.IntegerField(null=True, verbose_name='공시 종료일'),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='dcls_month',
            field=models.IntegerField(verbose_name='공시제출월'),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='dcls_strt_day',
            field=models.IntegerField(verbose_name='공시 시작일'),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_co_subm_day',
            field=models.IntegerField(verbose_name='금융회사 제출일'),
        ),
    ]
