# Generated by Django 4.2.16 on 2024-11-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_usersaving_save_trm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaving',
            name='save_trm',
            field=models.IntegerField(default=0, verbose_name='저축기간'),
        ),
    ]
