# Generated by Django 4.2.16 on 2024-11-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_usersaving_save_trm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaving',
            name='mtrt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
